/**
 * @author Bhavesh Venugopal
 * Request Logger Middleware Tests
 * Tests for requestLogger middleware functionality
 */

import { jest, describe, it, expect, beforeEach, beforeAll } from '@jest/globals';

// Mock logger before importing middleware
const mockCreateRequestLogger = jest.fn();
const mockLogHttp = jest.fn();
const mockLogPerformance = jest.fn();

jest.unstable_mockModule('../../utils/logger.js', () => ({
  createRequestLogger: mockCreateRequestLogger,
  logHttp: mockLogHttp,
  logPerformance: mockLogPerformance
}));

let requestLogger;
let loggerUtils;

beforeAll(async () => {
  requestLogger = await import('../requestLogger.js');
  loggerUtils = await import('../../utils/logger.js');
});

describe('Request Logger Middleware', () => {
  let req, res, next;
  let mockLogger;

  beforeEach(() => {
    jest.clearAllMocks();

    // Create mock logger
    mockLogger = {
      info: jest.fn(),
      error: jest.fn(),
      warn: jest.fn(),
      debug: jest.fn()
    };

    mockCreateRequestLogger.mockReturnValue(mockLogger);

    // Mock Express request
    req = {
      id: undefined, // Will be generated by middleware
      method: 'GET',
      originalUrl: '/api/v2/users',
      url: '/api/v2/users',
      path: '/api/v2/users',
      ip: '127.0.0.1',
      socket: { remoteAddress: '127.0.0.1' },
      get: jest.fn((header) => {
        if (header === 'User-Agent') return 'Mozilla/5.0';
        if (header === 'Content-Type') return 'application/json';
        if (header === 'Content-Length') return '100';
        return undefined;
      }),
      user: null
    };

    // Mock Express response
    const originalEnd = jest.fn();
    res = {
      statusCode: 200,
      end: originalEnd,
      get: jest.fn((header) => {
        if (header === 'Content-Length') return '100';
        return undefined;
      })
    };

    next = jest.fn();
  });

  describe('requestLogger', () => {
    it('should generate request ID if not present', () => {
      // Arrange
      req.id = undefined;

      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(req.id).toBeDefined();
      expect(typeof req.id).toBe('string');
      expect(req.id.startsWith('req-')).toBe(true);
    });

    it('should use existing request ID if present', () => {
      // Arrange
      req.id = 'existing-request-id';

      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(req.id).toBe('existing-request-id');
    });

    it('should create request logger and attach to req', () => {
      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(mockCreateRequestLogger).toHaveBeenCalled();
      expect(req.logger).toBe(mockLogger);
    });

    it('should log request start with correct information', () => {
      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(mockLogger.info).toHaveBeenCalledWith('Request started', {
        method: 'GET',
        url: '/api/v2/users',
        userAgent: 'Mozilla/5.0',
        ip: '127.0.0.1',
        headers: {
          'content-type': 'application/json',
          'authorization': undefined
        }
      });
    });

    it('should redact authorization header in logs', () => {
      // Arrange
      req.get = jest.fn((header) => {
        if (header === 'User-Agent') return 'Mozilla/5.0';
        if (header === 'Content-Type') return 'application/json';
        if (header === 'Authorization') return 'Bearer token123';
        return undefined;
      });

      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(mockLogger.info).toHaveBeenCalledWith('Request started', expect.objectContaining({
        headers: expect.objectContaining({
          'authorization': '[REDACTED]'
        })
      }));
    });

    it('should log request completion when response ends', () => {
      // Act
      requestLogger.requestLogger(req, res, next);
      res.end();

      // Assert
      expect(mockLogger.info).toHaveBeenCalledWith('Request completed', expect.objectContaining({
        method: 'GET',
        url: '/api/v2/users',
        statusCode: 200,
        contentLength: '100'
      }));
      // Duration will vary, just check it's a string ending in 'ms'
      const callArgs = mockLogger.info.mock.calls.find(call => call[0] === 'Request completed');
      expect(callArgs[1].duration).toMatch(/\d+ms/);
    });

    it('should log HTTP access log when response ends', () => {
      // Act
      requestLogger.requestLogger(req, res, next);
      res.end();

      // Assert
      expect(mockLogHttp).toHaveBeenCalledWith('GET /api/v2/users', expect.objectContaining({
        requestId: req.id,
        statusCode: 200,
        ip: '127.0.0.1',
        userAgent: 'Mozilla/5.0',
        userId: 'anonymous'
      }));
      // Duration will vary, just check it's a string ending in 'ms'
      const callArgs = mockLogHttp.mock.calls[0];
      expect(callArgs[1].duration).toMatch(/\d+ms/);
    });

    it('should log performance warning for slow requests (>1000ms)', async () => {
      // Arrange
      const startTime = Date.now();
      
      // Act
      requestLogger.requestLogger(req, res, next);
      
      // Wait for more than 1000ms before calling res.end
      await new Promise(resolve => setTimeout(resolve, 1100));
      res.end();

      // Assert
      expect(mockLogPerformance).toHaveBeenCalledWith('GET /api/v2/users', expect.any(Number), expect.objectContaining({
        requestId: req.id,
        statusCode: 200,
        userId: 'anonymous'
      }));
      // Check that duration is > 1000ms
      const callArgs = mockLogPerformance.mock.calls[0];
      expect(callArgs[1]).toBeGreaterThan(1000);
    });

    it('should not log performance warning for fast requests (<1000ms)', () => {
      // Arrange
      const startTime = Date.now();
      jest.spyOn(Date, 'now')
        .mockReturnValueOnce(startTime)
        .mockReturnValueOnce(startTime + 500); // 500ms

      // Act
      requestLogger.requestLogger(req, res, next);
      res.end();

      // Assert
      expect(mockLogPerformance).not.toHaveBeenCalled();

      Date.now.mockRestore();
    });

    it('should call original res.end after logging', () => {
      // Arrange
      const originalEnd = jest.fn();
      res.end = originalEnd;

      // Act
      requestLogger.requestLogger(req, res, next);
      res.end('chunk', 'encoding');

      // Assert
      expect(originalEnd).toHaveBeenCalledWith('chunk', 'encoding');
    });

    it('should call next() to continue middleware chain', () => {
      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(next).toHaveBeenCalledWith();
      expect(next).toHaveBeenCalledTimes(1);
    });

    it('should use user ID in logger if user is authenticated', () => {
      // Arrange
      req.user = { id: 'user-123' };

      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(mockCreateRequestLogger).toHaveBeenCalledWith(
        expect.any(String),
        'user-123',
        '127.0.0.1'
      );
    });

    it('should use socket remoteAddress as fallback for IP', () => {
      // Arrange
      req.ip = undefined;
      req.socket = { remoteAddress: '192.168.1.1' };

      // Act
      requestLogger.requestLogger(req, res, next);

      // Assert
      expect(mockCreateRequestLogger).toHaveBeenCalledWith(
        expect.any(String),
        'anonymous',
        '192.168.1.1'
      );
    });
  });

  describe('errorLogger (from requestLogger)', () => {
    it('should log error using request logger if available', () => {
      // Arrange
      req.logger = mockLogger;
      const error = new Error('Test error');
      error.statusCode = 500;

      // Act
      requestLogger.errorLogger(error, req, res, next);

      // Assert
      expect(mockLogger.error).toHaveBeenCalledWith('Request error occurred', {
        error: {
          message: 'Test error',
          stack: expect.any(String),
          name: 'Error'
        },
        method: 'GET',
        url: '/api/v2/users',
        statusCode: 500
      });
      expect(next).toHaveBeenCalledWith(error);
    });

    it('should create fallback logger if request logger not available', () => {
      // Arrange
      req.logger = undefined;
      const error = new Error('Test error');

      // Act
      requestLogger.errorLogger(error, req, res, next);

      // Assert
      expect(mockCreateRequestLogger).toHaveBeenCalledWith('unknown', 'system', 'unknown');
      expect(next).toHaveBeenCalledWith(error);
    });

    it('should pass error to next middleware', () => {
      // Arrange
      req.logger = mockLogger;
      const error = new Error('Test error');

      // Act
      requestLogger.errorLogger(error, req, res, next);

      // Assert
      expect(next).toHaveBeenCalledWith(error);
    });
  });
});

