/**
 * @author Bhavesh Venugopal
 * Error Code Constants
 * Standardized error codes for programmatic error handling
 * Use these constants instead of hardcoded strings
 */

export const ERROR_CODES = {
  // Validation Errors (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',
  INVALID_JSON: 'INVALID_JSON',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  BAD_REQUEST: 'BAD_REQUEST',
  
  // Authentication Errors (401)
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  
  // Authorization Errors (403)
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // Not Found Errors (404)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_USER_NOT_FOUND: 'COMPANY_USER_NOT_FOUND',
  COMPANY_ROLE_NOT_FOUND: 'COMPANY_ROLE_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  
  // Conflict Errors (409)
  DUPLICATE_FIELD: 'DUPLICATE_FIELD',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  
  // Session Errors (400)
  SESSION_ERROR: 'SESSION_ERROR',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  
  // Server Errors (500)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR'
};

